make type_name() optional
iresearch-toolkit/iresearch pull request #205
Opened 2020-09-29 16:42 UTC by gnusi

2020-09-29 16:42 UTC, gnusi commented
http://jenkins01.arangodb.biz:8080/view/PR/job/iresearch_s-pr/142/

2020-09-29 19:58 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/job/iresearch-release-s/1156/

2020-09-30 10:38 UTC, Dronplane requested changes

2020-09-30 10:38 UTC, Dronplane commented on core/utils/std.hpp
> +#define HAS_MEMBER(type, member) has_member_##member_v<type>
```suggestion
#define HAS_MEMBER(type, member) has_member_##member##_v<type>
```

2020-09-30 10:38 UTC, Dronplane commented on core/utils/std.hpp
> +    static constexpr bool value = sizeof(test<T>(0)) == sizeof(yes_type);  \
```suggestion
    static constexpr bool value = sizeof(test<typename std::remove_reference<typename std::remove_cv<T>::type>::type>(0)) == sizeof(yes_type);  \
```

2020-09-30 10:38 UTC, Dronplane commented on core/utils/std.hpp
> +    template<typename U> static yes_type test(decltype(&U::member_name));  \
```suggestion
    template<typename U> static yes_type test(decltype(&U::member));  \
```

2020-09-30 11:12 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/view/PR/job/iresearch_s-pr/144/

2020-09-30 18:28 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/view/PR/job/iresearch_s-pr/145/

2020-10-01 12:01 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/view/PR/job/iresearch_s-pr/148/

2020-10-01 14:06 UTC, merged