Feature/speedup automaton
iresearch-toolkit/iresearch pull request #236
Opened 2021-01-07 16:44 UTC by gnusi

2021-02-17 17:27 UTC, gnusi commented
http://jenkins01.arangodb.biz:8080/view/PR/job/iresearch_s-pr/176/

2021-02-17 19:22 UTC, gnusi commented
http://jenkins.arangodb.biz:8080/view/PR/job/iresearch_s-pr/179/

2021-02-18 12:03 UTC, gnusi commented
http://jenkins01.arangodb.biz:8080/view/PR/job/iresearch_s-pr/180/

2021-02-18 12:53 UTC, Dronplane requested changes

2021-02-18 12:53 UTC, Dronplane commented on core/utils/automaton.hpp
> +      uint32_t max;
We should swap min and max members for Big-Endian

2021-02-18 14:39 UTC, Dronplane approved these changes
LGTM

2021-02-18 14:39 UTC, Dronplane commented on tests/utils/levenshtein_utils_test.cpp
> +#include "draw-impl.h"
Do we really need this?

2021-02-18 15:44 UTC, gnusi commented
http://jenkins01.arangodb.biz:8080/view/PR/job/iresearch_s-pr/181/

2021-02-18 19:57 UTC, merged