Search 161
iresearch-toolkit/iresearch pull request #269
Opened 2021-06-23 10:54 UTC by alexbakharew

Draft PR

2021-06-23 14:55 UTC, gnusi commented on core/search/levenshtein_filter.hpp
> +  /// @brief compute levenshtein without prefix
match this number of characters from the beginning of the target regardless of edit distance

2021-06-23 14:55 UTC, gnusi commented on core/utils/levenshtein_utils.cpp
> +  for (; begin != prefix.end(); ) {
```suggestion
for (; begin != end; ) {
```

2021-06-23 14:55 UTC, gnusi commented on tests/index/index_levenshtein_tests.cpp
> +      assert_index(reader, description,  irs::ref_cast<irs::byte_type>(prefix), irs::ref_cast<irs::byte_type>(target));
we can use `bytes_ref::EMPTY` instead

2021-06-23 14:55 UTC, gnusi commented on core/utils/levenshtein_utils.cpp
> +    const byte_type* next = irs::utf8_utils::next(begin, end);
we don't need to use `irs::` namespace prefix in `irs` namespace

2021-06-23 16:26 UTC, gnusi commented on tests/utils/levenshtein_utils_test.cpp
> +  return assert_description(description, irs::ref_cast<irs::byte_type>(""_sr), target, candidates);
`irs::ref_cast<irs::byte_type>(""_sr)` -> `bytes_ref::EMPTY`

2021-06-24 13:54 UTC, gnusi requested changes

2021-06-24 13:54 UTC, gnusi commented on core/search/levenshtein_filter.hpp
> +  /// @brief match this number of characters from the beginning of the target regardless of edit distance
80 characters per line

2021-06-24 13:54 UTC, gnusi commented on core/search/levenshtein_filter.hpp
> +  bstring prefix;
the good practice is to sort structure member in descending order of their size, i.e. you have to put `prefix` right after `target`

2021-06-24 13:54 UTC, gnusi commented on core/search/levenshtein_filter.cpp
> +      return [target](
```suggestion
return [target = opts.prefix + opts.term](
```

2021-06-24 13:54 UTC, gnusi commented on core/search/levenshtein_filter.cpp
> +      target += term;
```
if (!prefix.empty() && !term.empty()) {
  bstring target;
  target.reserve(prefix.size() + term.size();
  target += prefix;
  target += term;
  return by_term::prepare(index, order, boost, field, target);
} 

return by_term::prepare(index, order, boost, field, prefix.empty() ? term : prefix);
```

2021-06-24 15:39 UTC, Dronplane approved these changes
LGTM

2021-06-24 15:55 UTC, gnusi approved these changes

2021-06-24 15:56 UTC, merged