Honor icu locale variant
iresearch-toolkit/iresearch pull request #297
Opened 2021-09-08 15:15 UTC by alexbakharew

Added support for variant in locale. Added new tests

2021-09-09 10:26 UTC, Dronplane requested changes

2021-09-09 10:26 UTC, Dronplane commented on core/analysis/collation_token_stream.cpp
> +std::string get_locale_name(const string_ref language,
Maybe move this function to locale_utils.hpp/cpp ?

2021-09-09 10:26 UTC, Dronplane commented on core/analysis/collation_token_stream.cpp
> +bool verify_icu_locale(const std::locale& locale) {
Maybe move this function to locale_utils.hpp/cpp ?

2021-09-09 10:26 UTC, Dronplane commented on core/analysis/collation_token_stream.cpp
> +    {
As general suggestion:  Let's move all locale object serializing / deserializing to the separate compilation unit. So we could use it later for other analyzers (like text, norm and so on)

2021-09-09 10:26 UTC, Dronplane commented on tests/analysis/collation_token_stream_test.cpp
> +TEST(collation_token_stream_test, check_variant) {
Please add tests for parsing different locale objects including invalid ones. 
(E.g.   R"({"locale": {"language" : "de",
                     "encoding" : true,
                     "variant" :  123232}}) )

2021-09-14 16:17 UTC, Dronplane commented on core/utils/icu_locale_utils.cpp
> +      "Language parameter is not specified or it is not a string",
Looks like we are missing '%s' format specifier somewhere

2021-09-14 16:17 UTC, Dronplane commented on core/utils/icu_locale_utils.cpp
> +      return false;
Should we write something to log in case of invalid type ?

2021-09-14 16:17 UTC, Dronplane commented on core/utils/icu_locale_utils.cpp
> +      return false;
Should we write something to log in case of invalid type ?

2021-09-14 16:17 UTC, Dronplane commented on core/utils/icu_locale_utils.cpp
> +  VPackObjectBuilder object(builder);
Do we really want this additional wrapper object? With this wrapper result of locale_to_vpack will not  be accepted by get_locale_from_vpack. that looks weird.

2021-09-14 22:01 UTC, gnusi requested changes

2021-09-14 22:01 UTC, gnusi commented on core/analysis/collation_token_stream.hpp
> +#include "unicode/locid.h"
this header has to be placed before iresearch headers as per guidelines, also use <> instead of quotes

2021-09-14 22:01 UTC, gnusi commented on core/utils/icu_locale_utils.hpp
> +#include <unicode/locid.h>
please honor guildelines
<system headers>
<external library headers>
<our own headers>

2021-09-14 22:01 UTC, gnusi commented on tests/utils/icu_locale_utils_tests.cpp
> +  class IcuLocaleUtilsTestSuite: public ::testing::Test {
why empty test class?

2021-09-15 16:55 UTC, Dronplane commented on core/utils/icu_locale_utils.cpp
> +    if (encoding != "utf-8") {
Suggest to make this check case insensitive. As "UTF-8" and "utf-8" are both valid in general. Maybe some "tolower" ?

2021-09-15 16:55 UTC, Dronplane commented on tests/analysis/collation_token_stream_test.cpp
> +    std::string out_str;
Unused?

2021-09-15 16:55 UTC, Dronplane commented on tests/analysis/collation_token_stream_test.cpp
> +    in_str.assign(in_vpack->slice().startAs<char>(), in_vpack->slice().byteSize());
irs::string_ref could be created the same way without intermediate string.

2021-09-15 16:55 UTC, Dronplane commented on tests/analysis/collation_token_stream_test.cpp
> +
Please add test cases:
language  and variant but no country
only variant
only country

2021-09-15 16:55 UTC, Dronplane commented on tests/analysis/collation_token_stream_test.cpp
> +    ASSERT_EQ(nullptr, irs::analysis::analyzers::get("collation", irs::type<irs::text_format::json>::get(), R"({ "locale" : {"language" : "de_DE", "variant" : "_phonebook", "encoding" : "utf-32"}})")
Please also include checks for invalid value types for language object members

2021-09-16 16:34 UTC, Dronplane requested changes

2021-09-16 16:34 UTC, Dronplane commented on core/utils/icu_locale_utils.cpp
> +      enc.assign(dot_pos + 1, at_pos); // encoding is located between '.' and '@' symbols
what if `dot_pos` is after `at_pos` ?  like in string "ru_RU@let.s.break.it"

2021-09-16 16:34 UTC, Dronplane commented on tests/utils/icu_locale_utils_tests.cpp
> +TEST(icu_locale_utils_test_suite, get_locale_from_str) {
Please add some tests  with totally malformed string to be sure we could safely handle such input (e.g. do not crash).
Like "@ru_De.utf-8" or ".@".

2021-09-17 10:08 UTC, Dronplane commented on tests/utils/icu_locale_utils_tests.cpp
> +    ASSERT_TRUE(get_locale_from_str(locale_name, locale, true, &unicode));
Please add test with the same input but "new" parsing mode. That's another corner case

2021-09-17 14:37 UTC, Dronplane commented on core/utils/icu_locale_utils.hpp
> +                         Unicode* encoding = nullptr,
```suggestion
                         Unicode* unicode = nullptr,
```

2021-09-17 14:37 UTC, Dronplane commented on core/utils/icu_locale_utils.hpp
> +                         std::string* = nullptr);
```suggestion
                         std::string* encoding = nullptr);
```

2021-09-17 14:37 UTC, Dronplane commented on core/utils/icu_locale_utils.hpp
> +                           Unicode* const unicode = nullptr);
```suggestion
                           Unicode* unicode = nullptr);
```

2021-09-17 15:10 UTC, Dronplane approved these changes
LGTM

2021-09-17 16:14 UTC, merged